//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaProducto
    {
        public long IdProducto { get; set; }
        public long IdEntrada { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> idSeccion { get; set; }
        public Nullable<long> cantidad { get; set; }
        public Nullable<long> Lote { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual Entrada Entrada { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
