//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaProducto
    {
        public long IdProducto { get; set; }
        public long IdSalida { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<long> Cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Salida Salida { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
